shortener/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
	url(r'^delete/(?P<short_url>[\w-]{3,15})/$', views.UrlDeleteView.as_view(), name='delete'),
	url(r'^about/$', views.AboutView.as_view(), name='about'),
	url(r'^(?P<short_url>[\w-]{3,15})/$', views.UrlRedirectView.as_view(), name='redirect'),
	url(r'^.*/$', views.fast_track_service, name='fast_track'),
]

urlShortener/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import UserRegistrationView, UserLoginView, LogoutView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register$', UserRegistrationView.as_view(), name='register'),
    url(r'^login$', UserLoginView.as_view(), name='loginUrl'),
    url(r'^logout$', LogoutView.as_view(), name='logoutUrl'),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('', include('pwa.urls')),
    url(r'^', include('shortener.urls')),
]

shortener/models.py
from django.db import models
from.utils import create_short_url
from django.conf import settings


class ShortenerManager(models.Manager):
	def all(self, *args, **kwargs):
		query_set = super().all(*args, **kwargs).filter(active=True)
		return query_set



class Shortener(models.Model):
	url = models.URLField(max_length=2048)
	short_url = models.CharField(max_length=20, unique=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	count = models.IntegerField(default=0)
	end_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
	active = models.BooleanField(default=True)
	objects = ShortenerManager()

	def save(self, *args, **kwargs):
		if self.short_url is None or self.short_url == "":
			self.short_url = create_short_url(self)
		super().save(*args, **kwargs)


	def __str__(self):
		return self.url


	def get_full_url(self):
		return 'https://slimtrim.co/{}'.format(self.short_url)

shortener/forms.py
import re
import string
from django import forms
from .models import Shortener
from django.core.validators import URLValidator



class SubmitUrlForm(forms.ModelForm):
	internal_name = ('profile', 'contact', 'about', 'disclaimer', 'sitemap.xml', 'robots.txt', 'favicon.ico')

	url = forms.CharField(max_length=200,
		label='Link to shorten',
		required=False,
		)

	short_url = forms.CharField(min_length=3, max_length=20, required=False)
	
	class Meta:
		model = Shortener
		fields = [
			'url',
			'short_url',
		]
		exclude = ["end_user"]

	
	def clean_url(self):
		url = self.cleaned_data['url']
		if len(url) == 0 or url is None:
			raise forms.ValidationError("Come on! Find some URL.")
		if not 'http://' in url and not 'https://' in url:
		    url = 'http://' + url
		url_validate = URLValidator()
		try:
			url_validate(url)
		except:
			raise forms.ValidationError("Please Enter a Valid URL")
		return url

	
	def clean_short_url(self):
		short_url = self.cleaned_data['short_url']
		if short_url:	
			if self.contains_whitespace(short_url):
				raise forms.ValidationError('Whitespaces are kinda awkward, Use "_" instead?')
			if self.contains_special_characters(short_url): 
				raise forms.ValidationError('Bummer! Special characters aren\'t special enough!')
			if short_url in SubmitUrlForm.internal_name:
				raise forms.ValidationError("Bummer! We love that word, Please choose another one.")
			exists = Shortener.objects.filter(short_url=short_url).exists()
			if exists:
				raise forms.ValidationError("Please Choose another short link. This '{}' already exists.".format(short_url))
		return short_url

	@staticmethod
	def contains_whitespace(s):
		return True in [c in s for c in string.whitespace]

	@staticmethod
	def contains_special_characters(s):
		regex = re.compile(r'^(\w|-){3,20}$')
		return not regex.match(s)

shortener/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Shortener
from .forms import SubmitUrlForm
from django.urls import reverse
from django.contrib import messages
from django.views.generic.edit import FormView, DeleteView
from django.http import JsonResponse
from django.db.models import F
from django.views.generic import ListView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.base import RedirectView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.validators import URLValidator


class HomeView(View):
	template_name = 'shortener/home.html'
	
	def get(self, request):
		form = SubmitUrlForm()
		context = {'form': form }
		return render(request, self.template_name, context)

	def post(self, request):
		form = SubmitUrlForm(request.POST)
		if form.is_valid():
			url = form.save(commit=False)
			user = None
			if request.user.is_authenticated():
				user = request.user
			url.end_user = user
			url.save()
			full_url = Shortener.objects.latest('created_at').get_full_url()
			data = {
			    'message': full_url
			}
			return JsonResponse(data)
		return JsonResponse(form.errors, status=400)



class ProfileView(LoginRequiredMixin, ListView):
	login_url = '/login'
	context_object_name = 'urls'
	template_name = 'shortener/profile.html'

	def get_queryset(self):
		return Shortener.objects.filter(end_user=self.request.user).order_by('-created_at')


class AboutView(TemplateView):
    template_name = 'shortener/about.html'


class UrlRedirectView(RedirectView):
	
	def get_redirect_url(self, short_url):
		url = get_object_or_404(Shortener, short_url=short_url)
		url.count = F('count') + 1
		url.save()
		return url


class UrlDeleteView(LoginRequiredMixin, DeleteView):
	login_url = '/login'
	model = Shortener
	template_name = 'shortener/confirm_delete.html'
	success_url = '/profile'

	def get_object(self, queryset=None):
		short_url = self.kwargs.get('short_url')
		return Shortener.objects.get(short_url=short_url)

	def get(self, request, *args, **kwargs):
		if not request.user == self.get_object().end_user:
			raise Http404
		return super().get(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		messages.success(request, 'Url Deleted successfully!')
		return super().post(request, *args, **kwargs)


def fast_track_service(request):
	fast_track_url = request.get_full_path()[1:].replace('/?','?')
	if 'favicon.ico' in fast_track_url or 'robots.txt' in fast_track_url:
		return HttpResponse()
	if fast_track_url[-1] == '/':
		fast_track_url = fast_track_url[:-1]
	url_validate = URLValidator()
	try:
		url_validate(fast_track_url)
	except:
		fast_track_url = 'http://' + fast_track_url
		try:
			url_validate(fast_track_url)
		except:
			raise Http404
	f_url = Shortener.objects.create(url=fast_track_url)
	return render(request, 'shortener/fast_track.html', {'f_url': f_url})

shortener/templates/shortener/about.html
{% extends 'shortener/layout.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-3 mx-auto">
		<div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="mohi7solanki"><a class="LI-simple-link" href='https://in.linkedin.com/in/mohi7solanki?trk=profile-badge'>Mohit Solanki</a></div>
	</div>
{% endblock %}

shortener/templates/shortener/confirm_delete.html
{% extends 'shortener/layout.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-6 col-md-6 mx-auto">
		<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete "{{ object.get_full_url }}" ?</p>
	    <div class="form-group mt-3">
		    <input type="submit" class="btn btn-sm btn-danger mr-4" value="Confirm"/>
		    <a href="/profile">Cancel</a>
	    </div>
	</form>

{% endblock %}

shortener/templates/shortener/fast_track.html
<!DOCTYPE html>
<html>
<head>
	<title>Slimtrim | Fast Track Service</title>
	<style type="text/css">
		body {
			background: #34e89e;  
			background: -webkit-linear-gradient(to right, #0f3443, #34e89e);  
			background: linear-gradient(to right, #0f3443, #34e89e);
			color: white;
			font-size: 300%;
		}

		.container{
		  display: flex;
		  justify-content: center;
		  align-items: center;
		  height: 100vh;
		}
	</style>
</head>
<body class="btn" data-clipboard-text={{ f_url.get_full_url }} onclick="goBack()">
	<div class="container">
	  <div class="flex-item">
	   <h4>Click Anywhere to copy the link and get back to your Page</h4>
	  </div>
	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
	<script type="text/javascript">
		new Clipboard('.btn');
		function goBack() {
		    window.history.back();
		}
	</script>
</body>
</html>

shortener/templates/shortener/home.html
{% extends 'shortener/layout.html' %}
{% load static %}

{% block style %}
<style type="text/css">
	.input-group {
	  flex-wrap: wrap!important;
	}

	.input-group .invalid-feedback {
	  flex-basis: 100%;
	}

	.input-group .input-group-addon:nth-child(3) {
	    border-left: 0!important;
	    border-right: 1px solid rgba(0,0,0,.15);
	    border-radius: .25rem!important;
	    border-top-left-radius: 0!important;
	    border-bottom-left-radius: 0!important;
	}

	#id_short_url{
		border-top-right-radius: .25rem;
		border-bottom-right-radius: .25rem;
	}

</style>
{% endblock %}

{% block content %}
<div class="row form">
	<div class="col-lg-6 col-md-8 col-sm-12 mx-auto">
		<form method="POST" class="my-ajax-form" data-url='{{ request.build_absolute_uri|safe }}' action="." novalidate>
		{% include 'shortener/url_form.html' %}
	    </form>
	</div>
</div>

<div class="row shorten_url" style="display: none;">
	<div class="col-sm-4 mx-auto">
		<div class="input-group">
		  <input type="text" id="foo" class="form-control" value="" readonly>
		  <span class="input-group-btn">
		    <button id="copy-button" class="btn btn-primary" data-clipboard-text="" type="button" data-toggle="tooltip" data-placement="bottom" title="Copied!">Copy</button>
		  </span>
		</div>
		<p class="lead mt-3">Have another link to shorten? <span class="ml-4"><a href="/">Yes</a></span></p>

	<div>
</div>
{% endblock %}

{% block script %}

<script type="text/javascript" src="{% static 'shortener/js/ajaxForm.js' %}"></script>

<script type="text/javascript" src="{% static 'shortener/js/clip.js' %}"></script>

{% endblock %}

shortener/templates/shortener/layout.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% progressive_web_app_meta %}
	<title>SlimTrim | Customize your links</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'shortener/css/style.css' %}">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Raleway:600" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
	{% block style %}
	{% endblock %}
</head>
<body>
	  <nav class="navbar navbar-expand-lg navbar-dark fixed-top mb-2" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/">Slimtrim</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

          	{% if request.user.is_authenticated %}
          		 <li class="nav-item">
	              <a class="nav-link " href="/profile">Profile</a>
	            </li>

	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="/about">About Us</a>
	            </li>
	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="/#contact">Contact Us</a>
	            </li>

	             <li class="nav-item">
	              <a class="nav-link " href="/logout">Sign Out</a>
	            </li>
            {% else %}
	            <li class="nav-item">
	              <a class="nav-link " href="/register">Sign up </a>
	            </li>
	            <li class="nav-item">
	              <a class="nav-link " href="/login">Sign in</a>
	            </li>

	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="/about">About Us</a>
	            </li>
	            <li class="nav-item">
	              <a class="nav-link js-scroll-trigger" href="/#contact">Contact Us</a>
	            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
	
	<div class="container">
		{% block messages %}
			{% include 'shortener/messages.html' %}
		{% endblock %}
		{% block content %}
		{% endblock %}
	</div>

	<script src="https://code.jquery.com/jquery-3.2.1.min.js">
	</script>

	<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous">
	</script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>

	<script type="text/javascript">
		$(".alert").alert()
	</script>

	{% block script %}
	{% endblock %}

</body>
</html>

shortener/templates/shortener/messages.html
{% if messages %}
<div class="row">
	<div class="col-lg-6 col-md-8 mx-auto">
    {% for message in messages %}
	   <div class="alert alert-success alert-dismissible fade show" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>
		  {{ message }}
		</div>
    {% endfor %}
	</div>
</div>		
{% endif %}

shortener/templates/shortener/profile.html
{% extends 'shortener/layout.html' %}

{% block messages %}
	{% if messages %}
		<div class="row">
			<div class="col-lg-10 col-md-10 mx-auto">
		    {% for message in messages %}
			   <div class="alert alert-success alert-dismissible fade show" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				  </button>
				  {{ message }}
				</div>
		    {% endfor %}
			</div>
		</div>		
		{% endif %}
		{% endblock %}
{% block content %}

{% if urls %}
	<div class="row" id="startchange">
		<div class="col-lg-10 col-md-10 mx-auto">
			<p class="h3">Click On the URL to delete it!</p>
			<table class="table table-hover table-responsive">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Url</th>
			      <th scope="col">short url</th>
			      <th scope="col">Hit Count</th>
			    </tr>
			  </thead>
			  <tbody>
			  	{% for url in urls %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td><a href="{% url 'delete' short_url=url.short_url %}" class="text-white">{{ url.get_full_url }}</a></td>
						<td>{{ url.short_url }}</td>
						<td>{{ url.count }}</td>
						{% endfor %}
					</tr>
			</table>
		</div>
	</div>

{% else %}
	<div class="row">
		<div class="col-lg-8 col-md-8 mx-auto text-center">
			<p class="h3">No shortened URL's yet!</p>
			<a class="lead text-center" href="/">Add Some?</a>
		</div>
	</div>
{% endif %}
{% endblock %}

{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$(window).scroll(function() { 
			if ($(document).scrollTop() > 50) { 
			  $(".navbar").css("background-color", "grey"); 
			} else {
			  $(".navbar").css("background-color", "transparent");
			}
		});
	});
	var ht = $('#startchange').height()
	if(ht > 590){
		$('body').css('padding-top',ht/2+ 'px');
	}
	</script>
{% endblock %}

shortener/templates/shortener/success.html
{% extends 'shortener/layout.html' %}


{% block content %}
<div class="row">
	<div class="col-sm-4 mx-auto">
		<div class="input-group">
		  <input type="text" id="foo" class="form-control" value="{{url}}" readonly>
		  <span class="input-group-btn">
		    <button id="copy-button" class="btn btn-primary" data-clipboard-text="{{ url }}" type="button" data-toggle="tooltip" data-placement="bottom" title="Copied!">Copy</button>
		  </span>
		</div>
	<div>
</div>
{% endblock %}


{% block script %}
<script type="text/javascript">
	var clipboard = new Clipboard('#copy-button');
	$('#copy-button').tooltip({
	  trigger: 'click',
	  placement: 'bottom'
	});

	function hideTooltip(btn) {
	  setTimeout(function() {
	    $(btn).tooltip('hide');
	  }, 1000);
	}

	function setTooltip(btn, message) {
	  $(btn).tooltip('hide')
	    .attr('data-original-title', message)
	    .tooltip('show');
	}

	clipboard.on('success', function(e) {
	  setTooltip(e.trigger, 'Copied!');
	  hideTooltip(e.trigger);
	});

	clipboard.on('error', function(e) {
	  setTooltip(e.trigger, 'Failed!');
	  hideTooltip(e.trigger);
	});

</script>
{% endblock %}

shortener/templates/shortener/url_form.html
{% load widget_tweaks %}
{% for hidden_field in form.hidden_fields %}
	{{ hidden_field }}
{% endfor %}

{% csrf_token %}

<div class="form-group">
    <label class="lead">{{form.url.label}}</label>
    {% render_field form.url class='form-control' placeholder='Paste a link to shorten it' autofocus=""%}
    <div class="invalid-feedback invalid_url custom">
	</div>
</div>
	<div class="form-group mb-4">
    <label>Customize your short link (optional):</label>
    <div class="input-group">
    	<span class="input-group-addon">https://slimtrim.co/</span>
    	{% render_field form.short_url class="form-control" %}
        <div class="invalid-feedback invalid_short_url custom"></div>
    </div>
	</div>
<button type="submit" class="btn btn-primary">Shorten</button>